#!/bin/bash
# Author: Xuan Wang
# Contact: xuan.wang22@imperial.ac.uk
# Date: 4 Dec 2022
# Description: This script runs the entire miniproject, including the Python script, the R script, the report and the reference file.
# All the results generated by the project can be found in the results directory.

# runs the python script of data preparation
ipython3 dataprocess.py

# runs the R script of model defining, model fitting and comparison
Rscript miniproject.R

# generates the report pdf
bash compilation.sh
echo "Process completed!"